const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("hanBurger", {
  getBootstrapData: () => ipcRenderer.invoke("bootstrap-data"),
  getProjectEntry: (projectId) => ipcRenderer.invoke("get-project-entry", projectId),
  signInWithGoogle: () => ipcRenderer.invoke("sign-in-google"),
  signOut: () => ipcRenderer.invoke("sign-out"),
  installProject: (projectId) => ipcRenderer.invoke("install-project", projectId),
  updateInstalledProjects: () => ipcRenderer.invoke("update-installed-projects"),
  removeProject: (projectId) => ipcRenderer.invoke("remove-project", projectId),
  getCalendarEvents: () => ipcRenderer.invoke("calendar-get-events"),
  saveCalendarEvents: (events) => ipcRenderer.invoke("calendar-save-events", events),
  downloadCalendarEvents: () => ipcRenderer.invoke("calendar-download-events"),
  uploadCalendarEvents: (events) => ipcRenderer.invoke("calendar-upload-events", events),
  openCalendarWidget: (theme) => ipcRenderer.invoke("calendar-open-widget", theme),
  closeCalendarWidget: () => ipcRenderer.invoke("calendar-close-widget"),
  triggerUpdateCheck: () => ipcRenderer.invoke("trigger-update-check"),
  restartAndInstallUpdate: () => ipcRenderer.invoke("restart-and-install-update"),
  listCrashReports: () => ipcRenderer.invoke("list-crash-reports"),
  readCrashReport: (filePath) => ipcRenderer.invoke("read-crash-report", filePath),
  exportCrashReport: (filePath) => ipcRenderer.invoke("export-crash-report", filePath),
  recordRendererError: (payload) => ipcRenderer.invoke("record-renderer-error", payload),
  minimizeWindow: () => ipcRenderer.invoke("window-minimize"),
  maximizeWindow: () => ipcRenderer.invoke("window-maximize"),
  closeWindow: () => ipcRenderer.invoke("window-close"),
  onAuthChanged: (callback) => ipcRenderer.on("auth-changed", (_event, payload) => callback(payload)),
  onProjectsChanged: (callback) => ipcRenderer.on("projects-changed", (_event, payload) => callback(payload)),
  onProjectUpdateStatus: (callback) => ipcRenderer.on("project-update-status", (_event, payload) => callback(payload)),
  onUpdateStatus: (callback) => ipcRenderer.on("update-status", (_event, payload) => callback(payload)),
  onCrashReportCreated: (callback) => ipcRenderer.on("crash-report-created", (_event, payload) => callback(payload)),
  onClosingSyncStatus: (callback) => ipcRenderer.on("closing-sync-status", (_event, payload) => callback(payload)),
  onWindowStateChanged: (callback) => ipcRenderer.on("window-state-changed", (_event, payload) => callback(payload))
});
